### ISSUE TITLE
Try XML when HTML fails?

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/urlfinderlib#53]
Small XLS/XML files that mime as html throw this for us a few dozen times a day. Urlfinder attempts to parse these files as html when parsing as xml solves the problem.

```
2021-08-04 16:37:09,479 root.<module> +23: ERROR    exception parsing 0010100708_0288.xls
Traceback (most recent call last):
  File "./local_urlfinder", line 19, in <module>
    urls = sorted(list(urlfinderlib.find_urls(f.read())))
  File "/data/home/smcfeely/dev/urlfinderlib/urlfinderlib/urlfinderlib.py", line 32, in find_urls
    urls += finders.HtmlUrlFinder(blob, base_url=base_url).find_urls()
  File "/data/home/smcfeely/dev/urlfinderlib/urlfinderlib/finders/html.py", line 67, in find_urls
    urls += HtmlTreeUrlFinder(string, base_url=self._base_url).find_urls()
  File "/data/home/smcfeely/dev/urlfinderlib/urlfinderlib/finders/html.py", line 77, in __init__
    self._tree = _build_tree(string)
  File "/data/home/smcfeely/dev/urlfinderlib/urlfinderlib/finders/html.py", line 24, in _build_tree
    tree = etree.parse(StringIO(string), parser=parser)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by automationator** [comment]
Fixed by #54
